"""Data Analysis, Pattern Detection, and Visualization Package for Citizen Grievance Portal.

Owner: YM (Data Analysis + Pattern Detection + Testing)

Provides descriptive statistics, explainable pattern and hotspot detection,
urgency score analytics, and automated chart generation for citizen complaint datasets.
"""

from analysis.analysis import (
    CORE_COLUMNS,
    EXPECTED_COLUMNS,
    REQUIRED_COLUMNS,
    VALID_CATEGORIES,
    VALID_DEPARTMENTS,
    VALID_PRIORITIES,
    count_by_category,
    count_by_department,
    count_by_location,
    count_by_priority,
    count_by_status,
    count_high_critical_complaints,
    count_repeated_complaints,
    find_hotspots,
    find_priority_concentration,
    find_recurring_patterns,
    find_repeated_complaints,
    find_unusually_frequent_categories,
    generate_charts,
    get_average_urgency_score,
    get_summary_statistics,
    get_top_category,
    get_top_department,
    get_top_locations,
    get_top_priority,
    get_total_complaints,
    load_complaints,
)
from analysis.urgency_score import (
    SEVERITY_WEIGHTS,
    POPULATION_WEIGHTS,
    calculate_urgency_score,
    get_urgency_level,
)

__all__ = [
    "CORE_COLUMNS",
    "EXPECTED_COLUMNS",
    "REQUIRED_COLUMNS",
    "VALID_CATEGORIES",
    "VALID_PRIORITIES",
    "VALID_DEPARTMENTS",
    "load_complaints",
    "get_total_complaints",
    "get_summary_statistics",
    "count_by_category",
    "count_by_priority",
    "count_by_department",
    "count_by_status",
    "count_by_location",
    "get_average_urgency_score",
    "count_high_critical_complaints",
    "count_repeated_complaints",
    "get_top_category",
    "get_top_priority",
    "get_top_department",
    "get_top_locations",
    "find_repeated_complaints",
    "find_hotspots",
    "find_priority_concentration",
    "find_unusually_frequent_categories",
    "find_recurring_patterns",
    "generate_charts",
    "SEVERITY_WEIGHTS",
    "POPULATION_WEIGHTS",
    "calculate_urgency_score",
    "get_urgency_level",
]
